version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn planet.application:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir src
